per_page: 6
length:
  course_type:
    maximum: 50
  course_title:
    maximum: 100
  quiz_name:
    maximum: 100
  lesson_name:
    maximum: 100
lesson_step:
  default: 1
mark:
  min: 1
  max: 10
comment:
  per_page: 10
default:
  lesson_type: 1
  lesson_sequence: 1
