users:
  per_page: 10
length:
  course_type:
    maximum: 50
  course_title:
    maximum: 100
  course_overview:
    maximum: 150
  quiz_name:
    maximum: 100
  lesson_name:
    maximum: 100
lesson_step:
  default: 1
mark:
  min: 5
comment:
  per_page: 10
register:
  per_page: 24
search:
  per_page: 10
default:
  lesson_type: 1
  lesson_sequence: 1
lesson_type: { video: 1, quiz: 2 }
provider:
  search: { "Athena": "athena", "Google": "google_oauth2", "Facebook": "facebook" }

# model user
user:
  max_length_full_name: 40
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  fullname_regex: !ruby/regexp '/\A[A-Za-z\s]+\z/' 
